name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_simu
      id: test_simu
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_simu
        setup-command: ''
        command: gradle test
        timeout: 5
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_SIMU_RESULTS: "${{steps.test_simu.outputs.result}}"
      with:
        runners: test_simu
